module.exports = (bot) => {
    bot.variables({
    allowence: "0",
    coring: "0",
uncoring: "0",
proposed: "0",
epring: "0",
myring: "0",
lering: "0",
faring: "0",
married: "false",
partner: "",
type: "0",
    alcap: "10",
    dacap: "100",
    wecap: "250",
    prefix: ".",
    embed_color: "FFE599",
    money: "cash",
    color: "FFE599",
    symbol: "<:green_cash_is_pog:915689556580388884>",
    cash: "0",
    bank: "0",
    rifle: "0",
    rod: "0",
    laptop: "0",
    pickaxe: "0",
    common: "0",
    uncommon: "0",
    rare: "0",
    legendary: "0",
    silver: "0",
    crystal: "0",
    ruby: "0",
    uranium: "0",
    sulphur: "0",
    worth: "0",
    promocode: "0",
    job: "none"
    }, "lexi")
}

